import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: "My Docs",
      social: {
        github: "https://github.com/withastro/starlight",
      },
      sidebar: [
        {
          label: "Start",
          items: [
            // Each item here is one entry in the navigation menu.
            {
              label: "Startseite",
              link: "/start/start",
            },
            {
              label: "Übersicht",
              link: "/start/overview",
            },
            {
              label: "Mithelfen",
              link: "/start/contribution",
            },
          ],
        },
        // Each subfolder inside /src/docs can be autogenerated like this.
        // Use
        {
          label: "Astro",
          autogenerate: { directory: "astro" },
        },
      ],
    }),
  ],
});
