name: Update Submodule

on:
  push:
    branches:
      - main

jobs:
  update_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodule
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Update submodule"
          git push